name: FocusFlow
options:
  bundleIdPrefix: com.zachthomas
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_VERSION: "5.9"
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_CFBundleDisplayName: "FocusFlow"
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  FocusFlow:
    type: application
    platform: iOS
    sources:
      - path: FocusFlow
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zachthomas.focusflow
        INFOPLIST_KEY_CFBundleDisplayName: "FocusFlow"
